Added ability to filter help by plugin name
ViacomInc/roku_builder pull request #29
Opened 2020-07-21 14:26 UTC by markwpearce

Can do `roku --help pluginName` to just get the help for a particular plugin

e.g.

```
% roku --help loader
RokuBuilder::Loader
Usage: roku [options]

Options for RokuBuilder::Loader:
Commands:
    -l, --sideload                   Sideload an app
    -d, --delete                     Delete the currently sideloaded app
    -b, --build                      Build a zip to be sideloaded
        --squash                     Convert currently sideloaded application to squashfs
Options:
    -x, --exclude                    Apply exclude config to sideload
        --remote-debug               Sideload will enable remote debug
```

2020-08-12 13:46 UTC, markwpearce commented on lib/roku_builder/plugins/core.rb
> +    def self.get_help_text(parser:, options:, plugin_name:)
I moved this to its own function so it can be tested --- you can't test a function easily with an "exit" call

2020-09-30 18:37 UTC, greeneca requested changes

2020-09-30 18:37 UTC, greeneca commented on lib/roku_builder/plugins/core.rb
> +      puts parser
This line needs to be removed I think.

2020-09-30 19:07 UTC, markwpearce commented on lib/roku_builder/plugins/core.rb
> +      puts parser
fixed

2021-03-23 04:40 UTC, bun100 approved these changes

2021-09-01 15:10 UTC, markwpearce commented
hey @greeneca ... Can we merge this?

2021-09-01 15:10 UTC, markwpearce commented
hey @greeneca ... Can we merge this?

2021-09-01 17:02 UTC, markwpearce commented
hey @greeneca ... Can we merge this?

2021-09-01 17:25 UTC, merged